# Generated by Django 2.2.7 on 2019-11-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='phot_url',
            new_name='photo_url',
        ),
    ]
